apiVersion: v1
kind: Service
metadata:
  name: {{ include "annotations-api.fullname" . }}
  
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "annotations-api.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http