services:
  app:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile
    command:
      bash -c "bash /tmp/scripts/wait-for-it.sh db:5432 --timeout=30 && poetry run uvicorn brokerage_service_api.api.app:app --host 0.0.0.0 --port 8081 --workers 5 --reload"
    restart: always
    env_file:
      - ../.env.local
    volumes:
      - ../:/code:Z
      - ../dockerfiles/scripts:/tmp/scripts
    ports:
      - "8081:8081"
    image: api:latest
    depends_on:
      - redis
      - db
    networks:
      - postgisapi_network

  annotations_api1:
    image: ghcr.io/paidiver/annotations-api:latest
    env_file:
      - ../.env.annotations1
    restart: always
    depends_on:
      - annotations_api_db1
    ports:
      - "8000:8000"
    command: >
      sh -c "bash /tmp/scripts/wait-for-it.sh db:5432 --timeout=30 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app:Z
      - ../docker/scripts:/tmp/scripts
    networks:
      - shared_services

  annotations_api2:
    image: ghcr.io/paidiver/annotations-api:latest
    env_file:
      - ../.env.annotations2
    restart: always
    depends_on:
      - annotations_api_db1
    ports:
      - "8001:8000"
    command: >
      sh -c "bash /tmp/scripts/wait-for-it.sh db:5432 --timeout=30 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app:Z
      - ../docker/scripts:/tmp/scripts
    networks:
      - shared_services

  annotations_seed_data1:
    image: ghcr.io/paidiver/annotations-api:latest
    env_file:
      - ../.env.annotations1
    restart: always
    depends_on:
      - annotations_api1
      - worms-cache-seed
    command: >
      sh -c "python manage.py seed_demo_data"
    volumes:
      - ../:/app:Z
      - ../docker/scripts:/tmp/scripts
    networks:
      - shared_services

  annotations_seed_data2:
    image: ghcr.io/paidiver/annotations-api:latest
    env_file:
      - ../.env.annotations2
    restart: always
    depends_on:
      - annotations_api2
      - worms-cache-seed
    command: >
      sh -c "python manage.py seed_demo_data"
    volumes:
      - ../:/app:Z
      - ../docker/scripts:/tmp/scripts
    networks:
      - shared_services


  annotations_api_db1:
    image: postgis/postgis:16-3.5
    container_name: annotations_api_db1
    restart: always
    env_file:
      - ../.env.annotations1
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - shared_services

  annotations_api_db2:
    image: postgis/postgis:16-3.5
    container_name: annotations_api_db2
    restart: always
    env_file:
      - ../.env.annotations2
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - shared_services

  worms-db:
    image: postgres:18
    container_name: worms_cache_db
    restart: always
    env_file:
      - ../.env.worms
    volumes:
      - worms_pg_data:/var/lib/postgresql
    ports:
      - "5437:5432"
    networks:
      - shared_services
  worms-cache:
    image: ghcr.io/paidiver/worms-cache:latest
    env_file:
      - ../.env.worms
    restart: always
    depends_on:
      - worms-db
    ports:
      - "8001:8000"
    command: >
      sh -c "bash /tmp/scripts/wait-for-it.sh worms-db:5432 --timeout=30 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app:Z
      - ../docker/scripts:/tmp/scripts
    networks:
      - shared_services

  worms-cache-seed:
    image: ghcr.io/paidiver/worms-cache:latest
    env_file:
      - ../.env.worms
    restart: always
    depends_on:
      - worms-db
    ports:
      - "8001:8000"
    command: >
      sh -c "python manage.py ingest_worms --file initial_aphia_ids.txt --add-ranks"
    volumes:
      - ../:/app:Z
      - ../docker/scripts:/tmp/scripts
    networks:
      - shared_services

  taxamatch:
    image: ghcr.io/paidiver/worms-cache:rb-latest
    environment:
      PORT: "8080"
      RACK_ENV: "development"
      PUMA_WORKERS: "1"
      PUMA_THREADS: "8"
      MAX_NAMES: "50"
      MAX_CANDIDATES_PER_NAME: "300"
    ports:
      - "8082:8080"
    volumes:
      - ../taxamatch_service:/app:Z
    restart: unless-stopped
    networks:
      - shared_services

volumes:
  pg_data:
  worms_pg_data:

networks:
  shared_services:
    external: true
