ingress:
  enabled: true
  host: api.paidiver-brokerage-service.noc.ac.uk
  path: ""
  ingressClassName: "nginx"
  tls:
    - secretName: letsencrypt-brokerage-service-api-dev
      hosts:
        - api.paidiver-brokerage-service.noc.ac.uk
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-brokerage-service-api-dev

resources:
  limits:
    cpu: 400m
    memory: 600Mi
  requests:
    cpu: 400m
    memory: 600Mi

image:
  tag: latest

env:
  bodcAnnotationsApiUrl: "https://annotations-api1.atlantis-viz.online/api"
  jnccAnnotationsApiUrl: "https://annotations-api2.atlantis-viz.online/api"
