apiVersion: v1
kind: Service
metadata:
  name: "{{ include "brokerage-service-api.fullname" . }}-service"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
    component: {{ .Values.componentName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
