replicaCount: 1

image:
  repository: ghcr.io/paidiver/brokerage-service-api
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecret: ""


container:
  port: 8020

componentName: brokerage-service-api

service:
  type: ClusterIP
  port: 80
  targetPort: 8020

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

securityContext:
  runAsUser: 1000

resources:
  limits:
    cpu: "50m"
    memory: "128Mi"
  requests:
    cpu: "20m"
    memory: "64Mi"

ingress:
  enabled: false

env:
  bodcAnnotationsApiUrl: "https://annotationsdev.bodc.ac.uk/api"
  jnccAnnotationsApiUrl: "https://annotations-api.paidiver.site"
