name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read
    uses: paidiver/brokerage-service/.github/workflows/reusable-python-tox-ci.yml@main
    with:
      environments: '["lint", "py313", "build"]'
